core/forms.py
#!/usr/bin/python2.4
# Copyright 2009 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""The forms presented for editing/creating model entities."""



# Supress pylint invalid import order
# pylint: disable-msg=C6203

import copy
import datetime
import logging
import time

from django import forms
from django.forms import formsets
from django.forms import  util as form_util
from django.utils import encoding
from django.utils import safestring
from django.utils import translation
from google.appengine.api import users
from google.appengine.ext import db
from google.appengine.ext import deferred


import settings
from core import models
from core import rule_engine
from core import rules
from core import timezone_helper
from core import utils

_ = translation.ugettext

# Department constants.
_DEPARTMENTS_TAGS = [c[0] for c in settings.FORM_DEPARTMENT_CHOICES]
_DEPARTMENT_DISPLAY = [_(c[1]) for c in settings.FORM_DEPARTMENT_CHOICES]
DEPARTMENT_CHOICES = [('', 'Choose a department')]
DEPARTMENT_CHOICES.extend(zip(_DEPARTMENTS_TAGS, _DEPARTMENT_DISPLAY))
DEPARTMENT_CHOICES_MAP = dict(zip(_DEPARTMENTS_TAGS, _DEPARTMENT_DISPLAY))

# Activity type constants.
_TYPES_TAG = ['instructor-led', 'video', 'webinar', 'quizz']
_TYPES_DISPLAY = [_('In-person'), _('Video'), _('Virtual classroom/webinar'),
                  _('Assesment or test')]
TYPE_CHOICES = zip(_TYPES_TAG, _TYPES_DISPLAY)
TYPE_CHOICES_MAP = dict(TYPE_CHOICES)

# Difficulty level constants.
_LEVEL_TAGS = ['introductory', 'moderate', 'advanced']
_LEVELS_DISPLAY = [_('Introductory'), _('Moderate'), _('Advanced')]
LEVEL_CHOICES = [('', _('Choose difficulty level'))]
LEVEL_CHOICES.extend(zip(_LEVEL_TAGS, _LEVELS_DISPLAY))
LEVEL_CHOICES_MAP = dict(LEVEL_CHOICES)

# Form error messages.
_INVALID_MSG_START_DATE = _('Enter a valid start date.')
_INVALID_MSG_START_TIME = _('Enter a valid start time.')
_INVALID_MSG_END_DATE = _('Enter a valid end date.')
_INVALID_MSG_END_TIME = _('Enter a valid end time.')
_MIN_LENGTH_MSG = _('Please be more descriptive.')
_REQUIRED_MSG_START_DATE = _('Start date is required.')
_REQUIRED_MSG_START_TIME = _('Start time is required.')
_REQUIRED_MSG_END_DATE = _('End date is required.')
_REQUIRED_MSG_END_TIME = _('End time is required.')

_PROGRAM_NAME_LOCK = 'program_first_write'  # Lock prefix for program write.


class SimpleRadioFieldRenderer(forms.widgets.RadioFieldRenderer):
  """Overriding the default rendering of django radio select widget.

  The default radio select widget creates the options as an unordered html list,
  this class overrides this behavior and places all of them in the same line.
  """

  def render(self):
    """Override base implementation. Called to generate widget html."""
    # Supress invalid method name, since overriding base class method.
    # pylint: disable-msg=C6409
    return safestring.mark_safe(
        u'\n'.join([encoding.force_unicode(w) for w in self])
    )


# Suppress pylint no explicit inheritance from base object
# pylint: disable-msg=C6601
# Suppress pylint use of super on old style class
# pylint: disable-msg=E1002


class SettingsForm(forms.Form):
  """Creates a form for user settings.

  Attributes:
    timezone: User timezone.
    location: User city location code ex:'us-mtv'
  """

  location = forms.ChoiceField(choices=(),
                               required=True, label=_('City location'))

  def __init__(self, *args, **kwargs):
    super(SettingsForm, self).__init__(*args, **kwargs)

    locations = timezone_helper.GetLocationCodes()
    locations_display = []
    for loc in locations:
      display = '%s (%s)' % (loc, timezone_helper.GetTimezoneForLocation(loc))
      locations_display.append(display)

    self.fields['location'].choices = zip(locations, locations_display)

  def UpdateSettings(self, user):
    """Updates user settings.

    Args:
      user: The models.GlearnUser who is using creating the program.
    """
    data = self.cleaned_data
    timezone = timezone_helper.GetTimezoneForLocation(data['location'])
    user.timezone = utils.Timezone(timezone)
    user.location = data['location']
    user.put()

  @staticmethod
  def BuildPostData(user):
    """Create the post data to seed the form from an existing user."""
    post_data = {}
    post_data['location'] = user.location
    return post_data


class ProgramForm(forms.Form):
  """Form used to create and edit a program.

  This form is used to collect property values for a models.Program object.

  Attributes:
    name: The string value corresponding to Program.name
    instruction_type: The string choice of instruction type of the program.
      Stored in Program.program_tags.
    contact_person: Comma separated list of people associated with this
      program.
    facilitators: Comma separated list of people who help set up the program.
    description: Hidden form field which stores program description.
    level: The string choice of level of difficulty of the program. Stored in
      Program.program_tags.
    department: The string department choice of which department this course is
      aimed for. Stored in Program.program_tags.
    allow_employee: Boolean indicating if an employee can attend the program.
    allow_intern: Boolean indicating if an intern can attend the program.
    allow_contractor: Boolean indicating if a contractor can attend the program.
    allow_vendor: Boolean indicating if a vendor can attend the program.
  """

  name = forms.CharField(widget=forms.TextInput(attrs={'size': 30}),
                         label=_('Title'))
  instruction_type = forms.ChoiceField(
      widget=forms.RadioSelect(renderer=SimpleRadioFieldRenderer),
      choices=TYPE_CHOICES, required=True,
      label=_('Activity type')
  )
  # The description field is hidden
  # Editor is used as helper for field content
  description = forms.CharField(widget=forms.HiddenInput(),
                                # Init with space otherwise some focus alignment
                                # issue with editor widget
                                initial=_('&nbsp;'),
                                min_length=10, label=_('Description'),
                                error_messages={'min_length': _MIN_LENGTH_MSG})
  level = forms.ChoiceField(choices=LEVEL_CHOICES, initial='', required=False,
                            label=_('Difficulty'))
  department = forms.ChoiceField(choices=DEPARTMENT_CHOICES, initial='',
                                 required=True, label=_('Offered by'))
  allow_employee = forms.BooleanField(initial=True,
                                      label=utils.EmployeeType.DISPLAY_MAP[
                                          utils.EmployeeType.EMPLOYEE],
                                      required=False)
  allow_intern = forms.BooleanField(initial=True,
                                    label=utils.EmployeeType.DISPLAY_MAP[
                                        utils.EmployeeType.INTERN],
                                    required=False)
  allow_contractor = forms.BooleanField(
      label=utils.EmployeeType.DISPLAY_MAP[utils.EmployeeType.CONTRACTOR],
      required=False)
  allow_vendor = forms.BooleanField(
      label=utils.EmployeeType.DISPLAY_MAP[utils.EmployeeType.VENDOR],
      required=False)
  allow_all = forms.BooleanField(label=_('None, allow everyone.'),
                                 required=False)
  contact_person = forms.CharField(widget=forms.TextInput(attrs={'size': 30}),
                                   label=_('Contact'), required=True)
  facilitator = forms.CharField(widget=forms.TextInput(attrs={'size': 30}),
                                label=_('Owners'), required=True)
  manager_approval = forms.BooleanField(
      label=_('Manager approval'), required=False)
  public_activity_creation = forms.BooleanField(
      label=_('Shared activity'), required=False)
  visible = forms.BooleanField(initial=True, label=_('Visible'),
                               required=False)

  def CreateOrUpdateProgram(self, current_user, program=None):
    """Creates or updates the program in the datastore from form data.

    This function should be called after the form validates the data format. The
    input data is used to construct or update the program properties and the
    entity is written to the datastore. Model specific checks are also performed
    before writing out the entity.

    Args:
      current_user: The user who is using ProgramForm to create the program.
      program: The program that needs to be updated with form data. If None then
          program doesn't exist and a new program needs to be created.

    Returns:
      The created program model object or None if data is invalid.
    """
    data = self.cleaned_data

    name = data['name'].strip()

    description = data['description'].strip()

    email_list = data['contact_person'].strip().split(',')
    contact_list = [utils.GetAppEngineUser(e.strip()) for e in email_list
                    if e.strip()]

    email_list = data['facilitator'].strip().split(',')
    facilitator_list = [utils.GetAppEngineUser(e.strip()) for e in email_list
                        if e.strip()]

    if not name:
      msg = [_('Invalid title')]
      self._errors['name'] = form_util.ValidationError(msg).messages

    if not contact_list or len(contact_list) > 1 or None in contact_list:
      msg = [_('Invalid email')]

core/templates/base.html
{% load format %}
<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}"
    xml:lang="{% firstof LANGUAGE_CODE 'en' %}"
    lang="{% firstof LANGUAGE_CODE 'en' %}">
  <head>
    <title>{% block title %}{% endblock %} Home</title>
    {% block css %}
    {% if debug %}
      <link rel="stylesheet" type="text/css" href="/styles/datepicker.css" />
      <link rel="stylesheet" type="text/css" href="/styles/main.css" />
      <link rel="stylesheet" type="text/css" href="/styles/dialog.css" />
      <link rel="stylesheet" type="text/css" href="/styles/roster.css" />
      <link rel="stylesheet" type="text/css" href="/styles/sessions.css" />
    {% else %}
      <link rel="stylesheet" type="text/css" href="/styles/styles_compiled_{% app_version %}.css" />
    {% endif %}
    {% endblock %}
    {% block extra-head %}{% endblock %}
    {% block js %}
      {% include "javascript.html" %}
    {% endblock %}
  </head>
  <body>
<div class="header">
  <div class="headerLinks">
    <div class="access">
    <!-- login and admin interface -->
      <div id="gbar">
        <div id="guser">
            {% if user.is_staff %}
              <a href="/admin/">Admin interface</a> |
            {% endif %}
            <span id="login">{{ user.username }}</span> |
            <a href="{% url Settings %}?referrer={{ request.get_full_path }}">Settings</a> |
            <a href="{% url django.contrib.auth.views.logout %}">Sign out</a> | <a target="blank" href="{% help_url %}">Help</a> |
            <a href="{% url SystemStatus %}">Status</a>
        </div>
      </div>
    </div>
    <!-- logo-->
    <div class="logo">
      <a href="/" id="logo"><img src="{% app_logo %}" /></a>
    </div>
    <div id="confirm-msg" class="confirm-msg{% if not confirm_msg %} hidden{% endif %}">
      {{ confirm_msg }}
      {% if explain_confirm_msg %}
        <img class="note" src="/images/question_mark.gif"
         title="{{ explain_confirm_msg }}" alt="explanation"/>
      {% endif %}
    </div>
    <div id="error-msg" style="{% app_errors_display %}" class="confirm-msg">
      {% app_errors %}
    </div>
  </div>
  <!-- search -->
  {% block search %}
  <div class="search">
    <form action="{% url Search %}" id="id-search-form" method="post" enctype="multipart/form-data">
      <table>
        <tr><td>
          <div class="search-box">
              <input type="text" size="35" name="search_text" value="{{ search_text }}" />
              <input name="searchButton" value="Search" type="submit" />
              <input type="button" value="Next month in {{ request.user.GetCityCode|upper}}" onClick="javascript:search.submitSearch('{{ request.user.location|upper }}', true);"/>
          </div>
          <div class="search-links">
            <div id="show-advanced-search" {% if search_show_advanced %}class="hidden"{% endif %}>
              <a onClick="javascript:search.showAdvancedSearch(true);">Add Filters</a>
            </div>
            <div id="hide-advanced-search" {% if not search_show_advanced %}class="hidden"{% endif %}>
              <a onClick="javascript:search.showAdvancedSearch(false);">Clear Filters</a>
            </div>
          </div>
        </td></tr>
        <tr>
          <td>
            <div class="search-options {% if not search_show_advanced %}hidden{% endif %}" id="advanced-search-div">
              <select id="id-search-locations" name="search_location">
              </select>
              <label for="id-search-start-date">Start Date</label>
              <input id="id-search-start-date" type="text" size="10" value="{{search_start_date}}" name="search_start_date"/>
              <label for="id-search-end-date">End Date</label>
              <input id="id-search-end-date" type="text" size="10" value="{{search_end_date}}" name="search_end_date"/>
            </div>
          </td>
        </tr>
        {% if search_error_list %}
        </tr><td>
          <ul class="errorlist">
            {% for error in search_error_list %}
              <li>{{error}}</li>
            {% endfor %}
          </ul>
        </td></tr>
        {% endif %}
      </table>
    </form>
  </div>
  {% endblock %}
</div>

<div class="clear"></div>

<div class="main">
  <table class="main">
    <tbody>
      <tr>
        <td id="menuTd" class="menuShown"><div id="menuDisplay" class="menuShown">
          {% block nav %}
          <div id="menu" class="menu"> <br />
            {% if user.CanCreateProgram %}
              <input type="button"
                  onClick="window.location='{% url CreateProgram %}?oncancel={{ request.get_full_path }}'" value="Create new activity" />
            {% endif %}
            <br />
            <br />
            <div class="optionsStatic">
              <div class="{% block nav-home-class %}{% endblock %}">
                <a href="{% url Home %}">My Activities</a>
              </div>
                <div class="tabbed-left-nav {% block nav-learning-class %}{% endblock %}">
                  <a href="{% url ShowLearning %}">Enrolled</a>
                </div>
                <div class="tabbed-left-nav {% block nav-teaching-class %}{% endblock %}">
                  <a href="{% url ShowTeaching %}">Teaching</a>
                </div>
                <div class="tabbed-left-nav {% block nav-owned-class %}{% endblock %}">
                  <a href="{% url ShowOwned %}">Managing</a>
                </div>
                <div class="{% block nav-all-activities-class %}{% endblock %}">
                  <a href="{% url ShowPrograms %}">All Activities</a>
                </div>
                <div class="{% block nav-approvals-class%}{% endblock %}">
                  <a href="{% url ShowManagerApprovals %}">Approvals</a>
                </div>
            </div>
          </div>
          {% endblock %}
        </td>
        <td class="content">
          <div class="border">
            <!-- content container -->
            <div class="contentHeader">
              <div class="title">
                {%block nav-title %}Home{%endblock%}
              </div>

              <!-- start of content-->
              <div class="clear"></div>
              <table class="container">
                <tbody>
                  <tr>
                    <td class="info">
                      {% block content %}
                      {% endblock %}
                    </td>
                  </tr>
                </tbody>
              </table>
              <!-- end of content -->
            </div>
            <!-- blue footer -->
            <div class="contentFooter">
              {% block content-footer %}
              <div class="empty"> &nbsp; </div>
              {% endblock %}
            </div>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <!-- footer -->
  <div class="footer">
    &copy;2009 Google
  </div>
</div>
  <script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  </script>
  <script type="text/javascript">
  try {
  var pageTracker = _gat._getTracker("UA-12241036-1");
  pageTracker._trackPageview();
  } catch(err) {}
  </script>
{% block search-js %}
  <script type="text/javascript">
    search.initializeLocations({% search_locations %}, "{{search_location}}");
    search.clearAdvancedOptions(false);
    sessions.addDatePicker("id-search-start-date");
    sessions.addDatePicker("id-search-end-date");
  </script>
{% endblock %}
</body>
</html>
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->

core/templates/calendar_schedule.html
<h3><a href='https://{{ hostname }}{% url ShowProgram program_key=program.key %}'>{{ program.name }}</a></h3>
<p>{{ program.description|safe|striptags }}</p>
{% if schedule.notes %}
  <h3>Notes:</h3>
  <p>{{ schedule.notes }}
{% endif %}
<p>If you would like to unregister please visit <a href='https://{{ hostname }}{% url ShowProgram program_key=program.key %}'>{{ program.name }}</a>.</p>
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->

core/templates/delete_activity_popup_form.html
<form action="{% url DeleteActivity activity_key=activity_key %}" id="id_form" method="post" enctype="multipart/form-data">

<input type="hidden" name="activity_key" value="{{ activity_key }}"/>

<p>Are you sure you want to delete this session?
 </p>
  
  {% if students_count %}

  There are currently {{ students_count }} users enrolled and will be unregistered.
 {% else %}
 There are currently no users enrolled.
 {% endif %}
 
</form>
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->

core/templates/email_enroll_rejected.html
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->
{% extends 'base_email.html' %}


{% block content %}
<p>
  {% ifequal register.user register.creator %}Your enrollment {% else %}Enrollment for {{register.user.email }} {% endifequal %} in <a href='https://{{ hostname }}{% url ShowActivity activity_key=register.activity.key %}'>{{ register.program.name }}</a> has been rejected.
</p>
{% endblock %}

{% block location %}
{% endblock %}

{% block footer %}
<p> Reasons for rejection:</p>
<ul>
  {% for reason in status_reasons %}
    <li> {{ reason }} </li>
  {% endfor %}
</ul>
{% endblock %}

core/templates/email_pending.html
{% extends 'base_email.html' %}


{% block content %}
<p>
  Your request for enrollment in <a href='https://{{ hostname }}{% url ShowActivity activity_key=register.activity.key %}'>{{ register.program.name }}</a> to the following time slots is pending:
</p>
{% endblock %}

{% block footer %}
<p>
Your request is pending/waiting for the following reasons:
</p>

<ul>
  {% for reason in status_reasons %}
    <li> {{ reason }} </li>
  {% endfor %}
</ul>

<p>
If you no longer want to be enrolled, go to the <a href='https://{{ hostname }}{% url ShowActivity activity_key=register.activity.key %}'>Activity page</a> to cancel your enrollment.
</p>
{% endblock %}
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->

core/templates/email_registration_update.html
{% extends 'base_email.html' %}

{% block content %}
<p>
<b>The activity <a href='https://{{ hostname }}{% url ShowActivity activity_key=register.activity.key %}'>{{ register.program.name }}</a> has been changed.</b>
</p>
{% endblock %}

{% block footer %}
<p>
  If you no longer want to be enrolled, go to the <a href='https://{{ hostname }}{% url ShowActivity activity_key=register.activity.key %}'>Activity page</a> to cancel your enrollment.
</p>
{% endblock %}
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->

core/templates/email_waitlisted.html
{% extends 'base_email.html' %}


{% block content %}
<p>
  You are {{ rank }} on the general waitlist for <a href='https://{{ hostname }}{% url ShowActivity activity_key=register.activity.key %}'>{{ register.program.name }}</a> with the following time slots:
</p>
{% endblock %}

{% block footer %}
<p>
Currently, the class can only accept {{ capacity }} Googlers.
Should there be a vacated spot in the class, you will be automatically enrolled from the
waitlist and receive an email confirmation.
</p>

<p>
If you no longer want to be enrolled, go to the <a href='https://{{ hostname }}{% url ShowActivity activity_key=register.activity.key %}'>Activity page</a> to cancel your enrollment.
</p>
{% endblock %}
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->

core/templates/program_form.html
{% extends 'base.html' %}
{% block extra-head %}
<style type="text/css">
/* parent container in which this page fits */
table.container td.info {
  padding: 1em;
}
</style>
{% endblock %}
{% block nav-title %}
{% if is_update %}
Edit activity
{% else %}
Create new activity
{% endif %}
{% endblock %}


{% block js %}
{% include "javascript-editor.html" %}
{% endblock %}


{% block content %}

<form action="" method="post" enctype="multipart/form-data">
<table id='program-form' class="forms">
  <tr>
    <th>{{ form.name.label_tag }}</th>
    <td> {{ form.name }} {{ form.name.errors }}
  </tr>
  <tr>
    <th>{{ form.instruction_type.label_tag }}</th>
    <td>
    <div id="types">
      {{ form.instruction_type }}
    </div>
     {{ form.instruction_type.errors }}
    </td>
  </tr>
  <tr>
    <th>{{ form.description.label_tag }}</th>
    <td><div id="description_toolbar"></div><div id="description_edit"></div>
    {{ form.description }} {{ form.description.errors }}</td>
  </tr>
  <tr>
    <th>{{ form.level.label_tag }}<div class="optional">optional</div></th>
    <td>
      {{ form.level }}  {{ form.level.errors }}
    </td>
  </tr>
  <tr>
    <th>Restricted to <img id='id_question_restricted' class='help-tooltip'
        src='/images/question_mark.gif'/></th>
    <td>
    <div id="restrictions">
      {{ form.allow_employee }} {{ form.allow_employee.label_tag }}
      {{ form.allow_intern }} {{ form.allow_intern.label_tag }}
      {{ form.allow_contractor }} {{ form.allow_contractor.label_tag }}
      {{ form.allow_vendor }} {{ form.allow_vendor.label_tag }}
      {{ form.allow_all }} {{ form.allow_all.label_tag }}
    </div>
    <div>{{ form.allow_employee.errors }}</div>
    </td>
  </tr>
  <tr>
    <th>{{ form.manager_approval.label_tag }} <img id='id_manager_approval'
        class='help-tooltip' src='/images/question_mark.gif'/></th>
    <td>{{ form.manager_approval }}  {{ form.manager_approval.errors }}
  </tr>
  <tr>
    <th>{{ form.public_activity_creation.label_tag }}
        <img id='id_public_activity_creation'
         class='help-tooltip' src='/images/question_mark.gif'/></th>
    <td>{{ form.public_activity_creation }}  {{ form.public_activity_creation.errors }}
  </tr>
  <tr>
    <th>{{ form.visible.label_tag }}
        <img id='id_visible'
         class='help-tooltip' src='/images/question_mark.gif'/></th>
    <td>{{ form.visible }}  {{ form.visible.errors }}
  </tr>
  <tr>
    <th>{{ form.facilitator.label_tag }} <img id='id_question_facilitator'
        class='help-tooltip' src='/images/question_mark.gif'/></th>
    <td>{{ form.facilitator }} {{ form.facilitator.errors }}
     <div class="hint">Comma separated list of emails</div></td>
  </tr>
  <tr>
    <th>{{ form.contact_person.label_tag }} <img id='id_question_contact'
        class='help-tooltip' src='/images/question_mark.gif'/></th>
    <td>{{ form.contact_person }} {{ form.contact_person.errors }}
    <div class="hint">Enter an email or mailing list address</div></td>
  </tr>
  <tr>
    <th>{{ form.department.label_tag }}</th>
    <td>{{ form.department }}  {{ form.department.errors }}
  </tr>
  <!-- TODO(user): Commented out for alpha. Need for beta.
  <tr>
    <th>Labels</th>
    <td>
      <span class="instructions">
        Add labels to your activity so Googlers can easily browse and find it.
        Select from existing labels or add your own labels.
      </span>
      <table id="label-actions">
        <tr>
          <td id="label-generator-action"><input type="button" value="Select labels" /><span class="hint">(Recommended)</span></td>
          <td id="label-user-input-action"><input type="text" size="15" /> <input type="button" value="Add label" />
        </tr>
      </table>
      Current labels:
      <div id="label-output">
      </div>
    </td>
  </tr>
  -->
  <tr>
    <th>
    </th>
    <td class='padding-top'>
      <input id='id_submit' type="submit" class='button-bold' value="{% if is_update %}Save{% else %}Create{% endif %}" />
      <input type="button" value="Cancel" onClick="window.location='{{ request.GET.oncancel }}'">
    </td>
  </tr>
</table>
</form>
<script type="text/javascript">
  // django standard is to use id_<field name> for field IDs
  // per http://docs.djangoproject.com/en/dev/topics/forms/
  editor.createTooltip('id_question_restricted', 'Restricts activity enrollment by employee type.');
  editor.createTooltip('id_question_contact', 'This email address will be listed as the point of contact for the activity. All gLearn-automated emails about this activity will appear to be from this address.');
  editor.createTooltip('id_question_facilitator', 'Owners usually coordinate the activity. They will be able to modify the activity as needed.');
  editor.createTooltip('id_manager_approval', 'Requires manager approval before users can enroll.');
  editor.createTooltip('id_public_activity_creation', 'Any user within your domain can schedule new sessions under this activity');
  editor.createTooltip('id_visible', 'Uncheck this if the activity and the associated sessions should be invisible for search/browsing.');

  new editor.Editor('description_edit','description_toolbar','id_description', 'id_submit');
</script>
{% endblock %}
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->

core/templates/register_popup_form.html
{% if users %}
<form action="{% url UserRegisterAjax %}" id="id_form" method="post" enctype="multipart/form-data">
{% else %}
<form action="{% url UserRegister %}" id="id_form" method="post" enctype="multipart/form-data">
{% endif %}
<input type="hidden" name="program_id" value="{{ program_key }}"/>
<input type="hidden" name="activity_id" value="{{ activity_key }}"/>
<input type="hidden" id='user_emails' value="{{ users }}" name="users"/>
<input type="hidden" value="{{ notify }}" name="notify"/>
<input type="hidden" value="{{ force_status }}" name="force_status"/>

  You have opted to register
  {% if users_count %}
  {{ users_count }} users
  {% endif %}
  for the following sessions: <br/><br/>
  <div align="center">
  <table>
   {% block timeslots %}
   {% endblock %}
  </table>
  </div>

</form>
<!--
Copyright 2010 Google Inc. All Rights Reserved.

Use of this source code is governed by an Apache 2.0 License.
See the COPYING file for details.
-->